# version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
      - qdrant
      
    working_dir: /app

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"

